version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - .:/app
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - local
  mongodb:
    image: mongo:4.4
    container_name: local_mongo
    ports:
      - "27017:27017"
    networks:
      - local

networks:
  local:
    driver: bridge
